### ISSUE TITLE
teetty maxes out its CPU core

### ISSUE THREAD

**Issue by mullikine** [mitsuhiko/teetty#9]
The CPU core is being maxed out after sending input to teetty. 

I assume it is polling the file which is responsible. It would be nice to eliminate the CPU usage using inotify.

On Linux, the GNU coreutils version of tail uses [inotify](https://en.wikipedia.org/wiki/Inotify) to block waiting for changed to the file. With FreeBSD, tail uses [kevent](https://www.freebsd.org/cgi/man.cgi?kqueue) to do the same. This will be better than repeatedly checking for changes and sleeping.

https://asciinema.org/a/548071

**Comment by mitsuhiko** [comment]
Quite curious why this is. I'm already `select()`-ing on the input file so presumably for some reason `select()` still reports it as ready.

**Comment by dimlev** [comment]
This cannot be a bug with `select()` right? Nix is a pretty thin layer on top of `libc::select()`. So that is out.

It also works properly when teetty receives input by the `read(STDIN_FILENO, &mut buf)` part of the loop.

It only starts to use 100% of the cpu after input is sent for the first time using the `in_file`. `select()` immediately returns `Ok(1)` without actually blocking until it receives data.

A possibly related stack exchange question about a pipe being reported as readable even though there is no data:

https://unix.stackexchange.com/a/591969

**Comment by mitsuhiko** [comment]
Bug is relative. `select()` is a pretty old and limited interface, i wouldn't be surprised if it does not behave like I would expect. I am not sure how to repro this. It does not appear that this is how macOS is behaving at least.

**Comment by dimlev** [comment]
> It does not appear that this is how macOS is behaving at least.

I've tested it under arch, ubuntu 20.04 and rocky 9. Same behaviour.

After reading [this](https://unix.stackexchange.com/a/414951) I tried re-opening the `in_file` after `read` returns `Ok(0)` and it seems to be working.

**Comment by mitsuhiko** [comment]
@dimlev i can try to play around with this but how did you reopen it? From scratch by path or is there another way?

**Comment by dimlev** [comment]
Yes from scratch by (hardcoded) path. Here is a [gist](https://gist.github.com/dimlev/4589262b20bdc09cf99baa539d547893)

**Comment by mitsuhiko** [comment]
I feel like I don’t understand why that would be necessary. I think that an alternative solution might be to ensure that the pipe is also opened for writing by teetty in which case I think that issue should also not happen. 

Eg: https://github.com/mitsuhiko/teetty/blob/83b4d8ed1b6181d0bab94ce2bc91d722787d8688/tty-spawn/src/lib.rs#L97 (also do `write(true)` there)

**Comment by dimlev** [comment]
You are correct. The `write(true)` fixes it for linux. Thank you @mitsuhiko.
